# Generated by Django 3.2.9 on 2022-01-05 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=100)),
                ('short_desc', models.CharField(max_length=200)),
                ('long_desc', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='Book')),
                ('trailer', models.FileField(blank=True, null=True, upload_to='Book_videos')),
            ],
        ),
    ]
