# Generated by Django 3.2.9 on 2022-01-12 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0002_auto_20220107_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='book',
            name='short_desc',
        ),
    ]
