# Generated by Django 3.2.9 on 2022-01-12 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0003_auto_20220112_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='short_desc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
