# Generated by Django 3.2.9 on 2022-01-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0004_book_short_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='trailer',
            field=models.URLField(blank=True, null=True),
        ),
    ]
