# Generated by Django 3.2.9 on 2022-01-12 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0005_alter_book_trailer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
