# Generated by Django 3.2.9 on 2022-01-19 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0006_alter_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
