# Generated by Django 3.2.9 on 2022-02-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0010_rename_characters_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='externalBuy',
            field=models.URLField(blank=True, null=True),
        ),
    ]
